CloudBackup.WebApp/Controllers/PlatformController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using CloudBackup.Database.Operations;
using CloudBackup.Database.ViewModel;
using CloudBackup.Database.ViewModel.CreateModel;
using CloudBackup.Database.ViewModel.DataTableModel;
using CloudBackup.WebPlatforms;
using CloudBackup.WebPlatforms.GoogleDrive;
using CloudBackup.WebApp.Core;
using Google.Apis.Auth.OAuth2;
using Google.Apis.Auth.OAuth2.Flows;
using Google.Apis.Auth.OAuth2.Responses;
using Google.Apis.Drive.v3;
using Google.Apis.Util.Store;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace CloudBackup.WebApp.Controllers
{
    public class PlatformController : BaseController
    {
        private IHostingEnvironment _env;


        public PlatformController(IMemoryCache cache, IHostingEnvironment env) : base(cache)
        {
            _env = env;

        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult New(string id)
        {
            int realId = WebUtilities.DecryptId(id, GetUserName(), GetOrganizationId());
            if (realId > 0)
            {
                PlatformInsertModel model = operations.Plan.GetPlanById(GetOrganizationId(), realId);
                model.HashedPlatformId = WebUtilities.EncryptId(model.Id, GetUserName(), GetOrganizationId());
                return View(model);
                //return View();
            }
            else
            {
                PlatformInsertModel model = new PlatformInsertModel();
                return View(model);
            }
        }
        [HttpPost]
        public IActionResult New(PlatformInsertModel model)
        {
            model.CloseModal = false;
            if (String.IsNullOrEmpty(model.Name))
            {
                TempData["Notification"] = WebUtilities.InsertNotification("Platform ismi boş geçilemez.");
                return View(model);
            }
            if (model.Type == Database.Enum.PlanType.Seçiniz)
            {
                TempData["Notification"] = WebUtilities.InsertNotification("Platform tipini seçiniz.");
                return View(model);
            }
            string jsonData = "";
            foreach (var item in Request.Form)
            {
                if (item.Key.StartsWith("Form:") == true)
                {
                    string header = item.Key.Replace("Form:", "");
                    string data = item.Value;
                    jsonData += "\"" + header + "\": \"" + data + "\",";
                }
            }
            if ((!String.IsNullOrEmpty(model.HashedPlatformId) && model.Type==Database.Enum.PlanType.GoogleDrive) || model.Type != Database.Enum.PlanType.GoogleDrive)
            {
                jsonData = jsonData.Substring(0, jsonData.Length - 1);
                jsonData = "{ " + jsonData + " }";

                model.JsonData = jsonData;
            }
            model.OrganizationId = GetOrganizationId();

            if (String.IsNullOrEmpty(model.HashedPlatformId))
            {
                model.OrganizationId = GetOrganizationId();




                int returnValue = operations.Plan.InsertPlatform(model);

                if (returnValue > 0)
                {
                    model.HashedPlatformId = WebUtilities.EncryptId(returnValue, GetUserName(), GetOrganizationId());
                    TempData["Notification"] = WebUtilities.InsertNotification("Cihaz başarılı bir şekilde eklenmiştir.");
                    model.CloseModal = true;
                    return View(model);
                }
                else
                {
                    TempData["Notification"] = WebUtilities.InsertNotification("Ekleme sırasında bir hata oluştu lütfen sistem yöneticisine başvurunuz.");
                    model.CloseModal = false;
                    return View(model);
                }
            }
            else
            {
                int realId = WebUtilities.DecryptId(WebUtility.UrlDecode(model.HashedPlatformId), GetUserName(), GetOrganizationId());
                if (realId > 0)
                {
                    model.CloseModal = true;
                    model.Id = realId;
                    operations.Plan.UpdatePlan(model, GetOrganizationId());
                    return View(model);
                }
                else
                {
                    TempData["Notification"] = WebUtilities.InsertNotification("Hatalı işlem lütfen pencereyi kapatıp tekrar deneyiniz.");
                    model.CloseModal = false;
                    return View(model);
                }
            }
        }


        public IActionResult AuthGoogleDrive()
        {

            return View();
        }
        [AllowAnonymous]
        public TokenResponse exchangeCode(string code, string redirectUri)
        {

            PlatformGoogle pg = new PlatformGoogle(_env.ContentRootPath);
            return pg.AuthCodeToAccessToken(code, redirectUri, "");

        }
        [AllowAnonymous]
        public ActionResult ReturnGoogleAuth(string code, string state)
        {
            TokenResponse trp = exchangeCode(code, "https://" + Request.Host.Value + "/Platform/ReturnGoogleAuth");

            int realPlanId = WebUtilities.DecryptId(state, GetUserName(), GetOrganizationId());

            var planData = operations.Plan.GetPlanById(GetOrganizationId(), realPlanId);

            dynamic dData = null;
            if (!String.IsNullOrEmpty(planData.JsonData))
                dData = JObject.Parse(planData.JsonData);

            List<KeyValuePair<string, string>> list = new List<KeyValuePair<string, string>>();
            list.Add(new KeyValuePair<string, string>("accountId", realPlanId.ToString()));
            list.Add(new KeyValuePair<string, string>("accessToken", trp.AccessToken));
            if (!String.IsNullOrEmpty(trp.RefreshToken))
                list.Add(new KeyValuePair<string, string>("refreshToken", trp.RefreshToken));
            else if (dData != null && dData.refreshToken != null)
                list.Add(new KeyValuePair<string, string>("refreshToken", dData.refreshToken));
            list.Add(new KeyValuePair<string, string>("tokenExpire", DateTime.Now.AddSeconds(trp.ExpiresInSeconds.Value).ToString()));
            string jsonData = "";
            foreach (var item in list)
            {

                string header = item.Key;
                string data = item.Value;
                jsonData += "\"" + header + "\": \"" + data + "\",";

            }
            jsonData = jsonData.Substring(0, jsonData.Length - 1);
            jsonData = "{ " + jsonData + " }";

            planData.JsonData = jsonData;
            operations.Plan.UpdatePlan(planData, GetOrganizationId());

            TempData["Notification"] = WebUtilities.InsertNotification(planData.Name + " Planı google eşleştirmesi tamamlanmıştır. ");
            return Redirect("/Home/Dashboard");
        }
        [AllowAnonymous]

        public ActionResult GetGoogleDriveAuthAsync(string devicePlanId)
        {

            PlatformGoogle pg = new PlatformGoogle(_env.ContentRootPath);
            pg.AuthRequestUrl(Request.Host.Value);

            return Redirect(pg.AuthRequestUrl(Request.Host.Value) + "&state=" + WebUtility.UrlEncode(devicePlanId));

        }



        public IActionResult _GoogleDrive(string id)
        {
            var drive = operations.Plan.GetPlanById(GetOrganizationId(), WebUtilities.DecryptId(id, GetUserName(), GetOrganizationId()));
            drive.HashedPlatformId = WebUtility.UrlEncode(id);
            if (drive != null)
            {
                return View(drive);
            }
            else
            {
                PlatformInsertModel model = new PlatformInsertModel();
                return View(model);
            }
        }
        public IActionResult _Amazons3(string id)
        {
            if (!String.IsNullOrEmpty(id))
            {
                var drive = operations.Plan.GetPlanById(GetOrganizationId(), WebUtilities.DecryptId(id, GetUserName(), GetOrganizationId()));
                drive.HashedPlatformId = WebUtility.UrlEncode(id);
                if (drive != null)
                {
                    return View(drive);
                }
                else
                {
                    PlatformInsertModel model = new PlatformInsertModel();
                    return View(model);
                }
            }
            else
            {
                PlatformInsertModel model = new PlatformInsertModel();
                return View(model);
            }
        }
        public int DeletePlatform(string id)
        {
            int count = operations.Device.PlanDeviceCount(WebUtilities.DecryptId(WebUtility.UrlDecode(id), GetUserName(), GetOrganizationId()), GetOrganizationId());
            if (count > 0)
            {
                TempData["Notification"] = WebUtilities.InsertNotification("Plana bağlı cihazlar olduğu için silinemez.");
                return -1;
            }

            operations.Plan.DeletePlan(WebUtilities.DecryptId(WebUtility.UrlDecode(id), GetUserName(), GetOrganizationId()), GetOrganizationId());
            return 1;
        }
        public IActionResult GetPlatformDatatable(JQueryDataTableParamModel param)
        {
            List<PlanListModel> list = operations.Plan.GetListModel(GetOrganizationId(), param.iDisplayStart, param.iDisplayLength);
            List<string[]> listReturn = new List<string[]>();

            foreach (var item in list)
            {
                listReturn.Add(new[] { item.Name, item.Type.ToString(), WebUtilities.EncryptId(item.Id, GetUserName(), GetOrganizationId()) });
            }

CloudBackup.WebApp/Views/Platform/Index.cshtml
@{

}
@section Scripts{
    <script src="../../bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="../../bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    <script src="/Scripts/platform_index.js"></script>
    <script>
        $(document).ready(function () {
            platform_index.init();
        });
    </script>
}
@section Heads {
    <link rel="stylesheet" href="../../bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">
}
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Platformlar
            <small>EBackup</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Platformlar</a></li>
        </ol>
    </section>
    <section class="content">

        <div class="box">
            <div class="box-header">
                <h3 class="box-title">Platform Listesi</h3>
            </div>

            <!-- /.box-header -->
            <div class="box-body">
                <div style="margin-bottom:10px; text-align:right;">
                    <a class="btn btn-success ModalPopup" data-post-url="/Platform/New" data-height="420px">Yeni Platform Ekle</a>
                </div>
                <table id="dtDevices" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Platform İsmi</th>
                            <th>Tipi</th>
                            <th>İşlem</th>
                        </tr>
                    </thead>
                    <tbody></tbody>

                </table>
            </div>
            <!-- /.box-body -->
        </div>

    </section>
</div>

CloudBackup.WebApp/Views/Platform/New.cshtml
@model CloudBackup.Database.ViewModel.CreateModel.PlatformInsertModel
@{
    Layout = "_ModalLayout";
}
@section Scripts{
<script src="~/Scripts/platform_new.js"></script>
    <script>
        $(document).ready(function () {
        platform_new.init('@Model.HashedPlatformId','@Model.Type');
        @if(Model.CloseModal)
        {
            @:top.$('#modal-').modal('toggle');
        }

        $(".CloseModal").click(function () {
                    top.$('#modal-').modal('toggle');
                });
        });
    </script>
}
@section Heads {

}

<div class="modal-header">
    <button type="button" class="close CloseModal" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Platform Ekle</h4>
</div>
<form role="form" asp-controller="Platform" asp-action="New">
    <div class="modal-body">
        <input type="hidden" asp-for="HashedPlatformId" />
        <!-- text input -->
        <div class="form-group">
            <label>Platform Adı </label>
            <input type="text" asp-for="Name" class="form-control" placeholder="Platform İsmi Giriniz">
        </div>
        <!-- text input -->
        <div class="form-group">
            <label>Platform Tipi </label>
            <select  class="form-control" asp-for="Type">
               
                @foreach(var item in Enum.GetValues(typeof( CloudBackup.Database.Enum.PlanType)))
                {
                    <option value="@((int)item)">@item.ToString()</option>

                }
            </select>
        </div>
        
        <div id="dvContent" style="@((String.IsNullOrEmpty(Model.HashedPlatformId) == true && Model.Type == CloudBackup.Database.Enum.PlanType.GoogleDrive) ? "display:none;" : "display:block;")"></div>


    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default pull-left CloseModal" data-dismiss="modal">Kapat</button>
        @if (String.IsNullOrEmpty(Model.HashedPlatformId))
        {
            <button type="submit" class="btn btn-primary">Ekle</button>
        }
        else
        {
            <button type="submit" class="btn btn-primary">Düzenle</button>
        }
    </div>

</form>

CloudBackup.WebApp/Views/Platform/_AmazonS3.cshtml
@model CloudBackup.Database.ViewModel.CreateModel.PlatformInsertModel
@using Newtonsoft.Json.Linq
@{
    Layout = null;
    dynamic d = null;
    if (Model.JsonData != null)
    {
        d = JObject.Parse(Model.JsonData);
    }

}
<script>

    $(document).ready(function () {

      
    });
</script>
<div class="form-group">
    <label>ApiAccessKey</label>
    <input type="text" id="Form:apiAccessKey" name="Form:apiAccessKey" value="@(Model.JsonData!=null ?  d.apiAccessKey : "")" class="form-control ApiAccessKey">
</div>
<div class="form-group">
    <label>ApiSecretKey</label>
    <input type="text" id="Form:apiSecretKey" name="Form:apiSecretKey" value="@(Model.JsonData!=null ?  d.apiSecretKey : "")" class="form-control ApiSecretKey">
</div>
<div class="form-group">
    <label>Region</label>
    <select id="Form:region" name="Form:region" class="form-control Region">
        @if ((Model.JsonData != null ? d.region : "") == "USWest1")
        {
            <option selected value="USWest1">USWest1</option>
        }
        else
        {
            <option value="USWest1">USWest1</option>
        }
        @if ((Model.JsonData != null ? d.region : "") == "USWest2")
        {
            <option selected value="USWest2">USWest2</option>
        }
        else
        {
            <option value="USWest2">USWest2</option>
        }
        @if ((Model.JsonData != null ? d.region : "") == "APNortheast1")
        {
            <option selected value="APNortheast1">APNortheast1</option>
        }
        else
        {
            <option value="APNortheast1">APNortheast1</option>
        }
        @if ((Model.JsonData != null ? d.region : "") == "APNortheast2")
        {
            <option selected value="APNortheast2">APNortheast2</option>
        }
        else
        {
            <option value="APNortheast2">APNortheast2</option>
        }
        @if ((Model.JsonData != null ? d.region : "") == "APSouth1")
        {
            <option selected value="APSouth1">APSouth1</option>
        }
        else
        {
            <option value="APSouth1">APSouth1</option>
        }
        @if ((Model.JsonData != null ? d.region : "") == "APSoutheast1")
        {
            <option selected value="APSoutheast1">APSoutheast1</option>
        }
        else
        {
            <option value="APSoutheast1">APSoutheast1</option>
        }
        @if ((Model.JsonData != null ? d.region : "") == "APSoutheast2")
        {
            <option selected value="APSoutheast2">APSoutheast2</option>
        }
        else
        {
            <option value="APSoutheast2">APSoutheast2</option>
        }
        @if ((Model.JsonData != null ? d.region : "") == "CACentral1")
        {
            <option selected value="CACentral1">CACentral1</option>
        }
        else
        {
            <option value="CACentral1">CACentral1</option>
        }
        @if ((Model.JsonData != null ? d.region : "") == "CNNorth1")
        {
            <option selected value="CNNorth1">CNNorth1</option>
        }
        else
        {
            <option value="CNNorth1">CNNorth1</option>
        }
        @if ((Model.JsonData != null ? d.region : "") == "CNNorthWest1")
        {
            <option selected value="CNNorthWest1">CNNorthWest1</option>
        }
        else
        {
            <option value="CNNorthWest1">CNNorthWest1</option>
        }
        @if ((Model.JsonData != null ? d.region : "") == "EUCentral1")
        {
            <option selected value="EUCentral1">EUCentral1</option>
        }
        else
        {
            <option value="EUCentral1">EUCentral1</option>
        }
        @if ((Model.JsonData != null ? d.region : "") == "EUWest1")
        {
            <option selected value="EUWest1">EUWest1</option>
        }
        else
        {
            <option value="EUWest1">EUWest1</option>
        }
        @if ((Model.JsonData != null ? d.region : "") == "EUWest2")
        {
            <option selected value="EUWest2">EUWest2</option>
        }
        else
        {
            <option value="EUWest2">EUWest2</option>
        }
        @if ((Model.JsonData != null ? d.region : "") == "EUWest3")
        {
            <option selected value="EUWest3">EUWest3</option>
        }
        else
        {
            <option value="EUWest3">EUWest3</option>
        }
        @if ((Model.JsonData != null ? d.region : "") == "SAEast1")
        {
            <option selected value="SAEast1">SAEast1</option>
        }
        else
        {
            <option value="SAEast1">SAEast1</option>
        }
        @if ((Model.JsonData != null ? d.region : "") == "USEast1")
        {
            <option selected value="USEast1">USEast1</option>
        }
        else
        {
            <option value="USEast1">USEast1</option>
        }
        @if ((Model.JsonData != null ? d.region : "") == "USEast2")
        {
            <option selected value="USEast2">USEast2</option>
        }
        else
        {
            <option value="USEast2">USEast2</option>
        }
        @if ((Model.JsonData != null ? d.region : "") == "USGovCloudWest1")
        {
            <option selected value="USGovCloudWest1">USGovCloudWest1</option>
        }
        else
        {
            <option value="USGovCloudWest1">USGovCloudWest1</option>
        }


    </select>
</div>

CloudBackup.WebApp/Views/Platform/_GoogleDrive.cshtml
@model CloudBackup.Database.ViewModel.CreateModel.PlatformInsertModel
@using Newtonsoft.Json.Linq
@{
    Layout = null;
    dynamic d = null;
    if (Model.JsonData != null)
    {
        d = JObject.Parse(Model.JsonData);
    }

}
<script>

    $(document).ready(function () {

        $('#googleDriveConnect').click(function () { 
            $.ajax({
                url: "/Platform/GetGoogleDriveAuthAsync",
                success: function (data) {
                    if (data) {
                        console.log(data);
                        $('.accountId').val(data.userName);
                        $('.accessToken').val(data.access_token);
                        $('.refreshToken').val(data.refresh_token);

                    }
                    else
                        alert('Bağlanamadı')
                }
            });
        });
       
    });
</script>
<div class="form-group">
    <label>Google Hesabını Bağla</label>
    <a class="form-control Button" target="_blank" id="googleDriveConnect" href="/Platform/GetGoogleDriveAuthAsync?devicePlanId=@Model.HashedPlatformId">Bağla</a>
</div>
<div class="form-group">
    <label>Google Hesabı </label>
    <input type="text" id="Form:accountId" name="Form:accountId" value="@(Model.JsonData!=null ?  d.accountId : "")" class="form-control accountId" >
</div>
<input type="hidden" id="Form:accessToken" name="Form:accessToken" value="@(Model.JsonData!=null ?  d.accessToken : "")" class="form-control accessToken" >
<input type="hidden" id="Form:refreshToken" name="Form:refreshToken" value="@(Model.JsonData!=null ?  d.refreshToken : "")" class="form-control refreshToken" >