CloudBackup.WebApp/Controllers/DeviceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading;
using System.Threading.Tasks;
using CloudBackup.Database.Operations;
using CloudBackup.Database.ViewModel;
using CloudBackup.Database.ViewModel.CreateModel;
using CloudBackup.Database.ViewModel.DataTableModel;
using CloudBackup.WebPlatforms;
using CloudBackup.WebPlatforms.GoogleDrive;
using CloudBackup.WebApp.Core;
using Google.Apis.Auth.OAuth2;
using Google.Apis.Drive.v3;
using Google.Apis.Util.Store;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using CloudBackup.WebPlatforms.AmazonS3;

namespace CloudBackup.WebApp.Controllers
{
    public class TreeViewClass
    {
        public string id { get; set; }
        public string text { get; set; }
        public bool children { get; set; }
    }
    public class DeviceController : BaseController
    {

        public DeviceController(IMemoryCache cache, IHostingEnvironment env) : base(cache)
        {
            _env = env;
        }
        private IHostingEnvironment _env;


        public IActionResult GetDeviceDatatable(JQueryDataTableParamModel param)
        {
            List<DeviceListModel> list = operations.Device.GetListModel(GetOrganizationId(), param.iDisplayStart, param.iDisplayLength);
            List<string[]> listReturn = new List<string[]>();

            foreach (var item in list)
            {
                listReturn.Add(new[] { item.Name, item.LastProcessTime.HasValue == true ? item.LastProcessTime.Value.ToString() : "", item.CreatedDate.HasValue == true ? item.CreatedDate.Value.ToString() : "", item.DeviceStatus.ToString(), WebUtilities.EncryptId(item.Id, GetUserName(), GetOrganizationId()) });
            }
            int count = 0;
            if (list != null && list.Count > 0)
                count = list.FirstOrDefault().Count;

            return Json(new
            {
                sEcho = param.sEcho,
                iTotalRecords = count,
                iTotalDisplayRecords = count,
                aaData = listReturn
            });

        }
        public IActionResult GetDeviceJobDatatable(JQueryDataTableParamModel param)
        {
            List<DevicePlanListModel> list = operations.DevicePlan.GetListModel(GetOrganizationId(), param.iDisplayStart, param.iDisplayLength, WebUtilities.DecryptId(WebUtility.UrlDecode(Request.Query["deviceId"]), GetUserName(), GetOrganizationId()));
            List<string[]> listReturn = new List<string[]>();

            foreach (var item in list)
            {
                string retryPlan = "";

                CloudBackup.Database.Enum.RetryPlan pl = ((CloudBackup.Database.Enum.RetryPlan)Convert.ToInt32(item.RetryPlan));
                if (pl == CloudBackup.Database.Enum.RetryPlan.OneTime)
                {
                    retryPlan = "Bir kere";
                }
                if (pl == CloudBackup.Database.Enum.RetryPlan.Minute30)
                {
                    retryPlan = "30 dakika da bir";
                }
                else if (pl == CloudBackup.Database.Enum.RetryPlan.Hour1)
                {
                    retryPlan = "Her saat";
                }
                else if (pl == CloudBackup.Database.Enum.RetryPlan.Hour3)
                {
                    retryPlan = "3 saate bir";
                }
                else if (pl == CloudBackup.Database.Enum.RetryPlan.Hour6)
                {
                    retryPlan = "6 saate bir";
                }
                else if (pl == CloudBackup.Database.Enum.RetryPlan.Hour12)
                {
                    retryPlan = "12 saate bir";
                }
                else if (pl == CloudBackup.Database.Enum.RetryPlan.Day1)
                {
                    retryPlan = "Her Gün";
                }
                else if (pl == CloudBackup.Database.Enum.RetryPlan.Day2)
                {
                    retryPlan = "2 günde bir";
                }
                else if (pl == CloudBackup.Database.Enum.RetryPlan.Day3)
                {
                    retryPlan = "3 günde bir";
                }
                else if (pl == CloudBackup.Database.Enum.RetryPlan.Day4)
                {
                    retryPlan = "4 günde bir";
                }
                else if (pl == CloudBackup.Database.Enum.RetryPlan.Day5)
                {
                    retryPlan = "5 günde bir";
                }
                else if (pl == CloudBackup.Database.Enum.RetryPlan.Day6)
                {
                    retryPlan = "6 günde bir";
                }
                else if (pl == CloudBackup.Database.Enum.RetryPlan.Day7)
                {
                    retryPlan = "7 günde bir";
                }
                else if (pl == CloudBackup.Database.Enum.RetryPlan.Day8)
                {
                    retryPlan = "8 günde bir";
                }
                else if (pl == CloudBackup.Database.Enum.RetryPlan.Day9)
                {
                    retryPlan = "9 günde bir";
                }
                else if (pl == CloudBackup.Database.Enum.RetryPlan.Day10)
                {
                    retryPlan = "10 günde bir";
                }
                else if (pl == CloudBackup.Database.Enum.RetryPlan.Month1)
                {
                    retryPlan = "Ayda bir";
                }
                else if (pl == CloudBackup.Database.Enum.RetryPlan.Month2)
                {
                    retryPlan = "2 ayda bir";
                }
                else if (pl == CloudBackup.Database.Enum.RetryPlan.Month3)
                {
                    retryPlan = "3 ayda bir";
                }
                else if (pl == CloudBackup.Database.Enum.RetryPlan.Month4)
                {
                    retryPlan = "4 ayda bir";
                }
                else if (pl == CloudBackup.Database.Enum.RetryPlan.Year1)
                {
                    retryPlan = "Senede bir";
                }



                listReturn.Add(new[] { item.Name, item.Description, item.PlanName, retryPlan, item.LastProcessTime.HasValue == true ? item.LastProcessTime.Value.ToString() : "", WebUtilities.EncryptId(item.Id, GetUserName(), GetOrganizationId()) });
            }
            int count = 0;
            if (list != null && list.Count > 0)
                count = list.FirstOrDefault().Count;

            return Json(new
            {
                sEcho = param.sEcho,
                iTotalRecords = count,
                iTotalDisplayRecords = count,
                aaData = listReturn
            });

        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult New(string id)
        {
            int realId = WebUtilities.DecryptId(id, GetUserName(), GetOrganizationId());
            if (realId > 0)
            {
                DeviceInsertModel model = operations.Device.GetDeviceById(GetOrganizationId(), realId);
                model.HashedDeviceId = WebUtilities.EncryptId(model.DeviceId, GetUserName(), GetOrganizationId());
                return View(model);
            }
            else
            {
                DeviceInsertModel model = new DeviceInsertModel();
                return View(model);
            }
        }
        public List<LogListModel> GetLogModelList(int skip, int take, int devicePlanId = 0)
        {
            return operations.Log.GetListModel(GetOrganizationId(), devicePlanId, skip, take);
        }
        public IActionResult GetLogDatatableWithDevicePlanId(JQueryDataTableParamModel param)
        {
            int devicePlanId = 0;
            if (!String.IsNullOrEmpty(Request.Query["devicePlanId"]))
                devicePlanId = WebUtilities.DecryptId(WebUtility.UrlDecode(Request.Query["devicePlanId"]), GetUserName(), GetOrganizationId());
            List<LogListModel> list = GetLogModelList(param.iDisplayStart, param.iDisplayLength, devicePlanId);
            List<string[]> listReturn = new List<string[]>();

            if (devicePlanId > 0)
                foreach (var item in list)
                {
                    listReturn.Add(new[] { item.ProcessDate.ToString(), item.LogText });
                }
            else
                foreach (var item in list)
                {
                    listReturn.Add(new[] { item.ProcessDate.ToString(), item.DeviceName, item.PlanName, item.LogText });
                }
            int count = 0;
            if (list != null && list.Count > 0)
                count = list.FirstOrDefault().Count;

            return Json(new
            {
                sEcho = param.sEcho,
                iTotalRecords = count,
                iTotalDisplayRecords = count,
                aaData = listReturn
            });

        }
        public IActionResult ReloadApiInformation(string id)
        {
            operations.Device.ResetKeyAndAccesKey(GetOrganizationId(), WebUtilities.DecryptId(id, GetUserName(), GetOrganizationId()));
            return Redirect("/Device/Information?id=" + WebUtility.UrlEncode(id));
        }
        [HttpPost]
        public IActionResult New(DeviceInsertModel model)
        {

            model.CloseModal = false;
            if (String.IsNullOrEmpty(model.DeviceName) || String.IsNullOrEmpty(model.DeviceDescription))
            {
                TempData["Notification"] = WebUtilities.InsertNotification("Cihaz ismi ve açıklaması boş geçilemez.");
                return View(model);
            }
            if (String.IsNullOrEmpty(model.HashedDeviceId))
            {
                int returnValue = operations.Device.InsertJob(GetOrganizationId(), model.DeviceName, model.DeviceDescription);

                if (returnValue > 0)
                {

CloudBackup.WebApp/Views/Device/AllJobLog.cshtml
@{

}
@section Scripts{
    <script src="../../bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="../../bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    <script src="/Scripts/device_alljoblog.js"></script>
    <script>
        $(document).ready(function () {
            device_alljoblog.init();
        });
    </script>
}
@section Heads {
    <link rel="stylesheet" href="../../bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">
}
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Tüm Kayıtlar
            <small>EBackup</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Kayıtlar</a></li>
        </ol>
    </section>
    <section class="content">

        <div class="box">
            <div class="box-header">
                <h3 class="box-title">Kayıtlar</h3>
            </div>

            <!-- /.box-header -->
            <div class="box-body">

                <table id="dtDevices" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>İşlem Tarihi</th>
                            <th>Cihaz</th>
                            <th>Plan İsmi</th>
                            <th>Yapılan İşlem</th>
                        </tr>
                    </thead>
                    <tbody>
                      
                    </tbody>

                </table>
            </div>
            <!-- /.box-body -->
        </div>

    </section>
</div>

CloudBackup.WebApp/Views/Device/DeviceJobLog.cshtml
@model CloudBackup.Database.ViewModel.CreateModel.DevicePlanInsertModel
@{

}
@section Scripts{
    <script src="../../bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="../../bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    <script src="/Scripts/device_devicejoblog.js"></script>
    <script>
        $(document).ready(function () {
            device_devicejoblog.init('@ViewBag.DevicePlanId');
        });
    </script>
}
@section Heads {
    <link rel="stylesheet" href="../../bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">
}
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            @Model.Name Kayıtları 
            <small>EBackup</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Kayıtlar</a></li>
        </ol>
    </section>
    <section class="content">

        <div class="box">
            <div class="box-header">
                <h3 class="box-title">Kayıtlar</h3>
            </div>

            <!-- /.box-header -->
            <div class="box-body">
               
                <table id="dtDevices" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>İşlem Tarihi</th>
                            <th>Yapılan İşlem</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                30.08.2018 03:00:00
                            </td>
                            <td>Evdeki Bilgisayar</td>
                        </tr>
                        <tr>
                            <td>
                                30.08.2018 03:00:00
                            </td>
                            <td>Evdeki Bilgisayar</td>
                        </tr>
                        <tr>
                            <td>
                                30.08.2018 03:00:00
                            </td>
                            <td>Evdeki Bilgisayar</td>
                        </tr>
                        <tr>
                            <td>
                                30.08.2018 03:00:00
                            </td>
                            <td>Evdeki Bilgisayar</td>
                        </tr>
                        <tr>
                            <td>
                                30.08.2018 03:00:00
                            </td>
                            <td>Evdeki Bilgisayar</td>
                        </tr>



                    </tbody>

                </table>
            </div>
            <!-- /.box-body -->
        </div>

    </section>
</div>

CloudBackup.WebApp/Views/Device/DirectoryListing.cshtml
@{
    Layout = "_ModalLayout";
}
@section Scripts{
<script src="~/jstree/jstree.js"></script>
<script src="~/Scripts/device_directorylisting.js"></script>
    <script>
        $(document).ready(function () {
         $(".CloseModal").click(function () {
                    parent.$('#modal-').modal('toggle');
            });
            
            device_directorylisting.init(common.GetUrlVars()["htmlElement"], '@ViewBag.DeviceId','@ViewBag.CloudId');
        });
    </script>
}
@section Heads {
    <link href="~/jstree/themes/default/style.css" rel="stylesheet" />
}
<input type="hidden" id="selectedDirectory" />
<div class="modal-header">
    <button type="button" class="close CloseModal" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Klasör Listesi</h4>
</div>

<div class="modal-body">

    @*<div><span style="font-style:italic; margin-right:5px;"> Son Güncellenme Tarihi : 23.09.2018 </span> <button class="btn btn-primary btn-xs ClickRefresh">Yenile</button></div>*@
    <div id="treeView">
        <ul>
            <li>
                Root node 1
               
            </li>
        </ul>
    </div>

</div>
<div class="modal-footer">
    <button type="button" class="btn btn-default pull-left CloseModal" data-dismiss="modal">Kapat</button>
    <button id="btnChoose" type="button" class="btn btn-primary">Seç</button>
</div>

CloudBackup.WebApp/Views/Device/Download.cshtml
@section Scripts{}
@section Heads {}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            İndirmeler
            <small></small>
        </h1>
      
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- row -->
        <div class="row">
            <div class="col-md-12">
                <!-- The time line -->
                <ul class="timeline">
                    <!-- timeline time label -->
                    <li class="time-label">
                        <span class="bg-red">
                         29.12.2018
                        </span>
                    </li>
                    <!-- /.timeline-label -->
                    <!-- timeline item -->
                    <li>
                        <i class="fa fa-envelope bg-blue"></i>
                        <div class="timeline-item">
                            <span class="time"><i class="fa fa-clock-o"></i> 14:00 </span>
                            <h3 class="timeline-header"><a href="#">Yeni Versiyon v1.0.1 Yayınlandı. </a></h3>
                            <div class="timeline-body">
                                Amazon S3 entegrasyonu yapıldı.<br />
                                Dosya silmede yaşanan problem giderildi.<br />
                                Alt klasörlerdeki dosya güncelleme sorunu düzeltildi.<br />
                                
                            </div>
                            <div class="timeline-footer">
                                <a href="https://api.ebackup.cloud/Downloads/v1.0.1.rar" class="btn btn-primary btn-xs">İndir</a>
                              
                            </div>
                        </div>
                    </li>
                    <!-- END timeline item -->
                   
                    <li>
                        <i class="fa fa-clock-o bg-gray"></i>
                    </li>
                </ul>
            </div>
            <!-- /.col -->
        </div>
      
    </section>
    <!-- /.content -->
</div>

CloudBackup.WebApp/Views/Device/Index.cshtml
@{

}
@section Scripts{
    <script src="../../bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="../../bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    <script src="/Scripts/device_index.js"></script>
    <script>
        $(document).ready(function () {
            device_index.init();
        });
    </script>
}
@section Heads {
    <link rel="stylesheet" href="../../bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">
}
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Cihazlar
            <small>EBackup</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Cihazlar</a></li>
        </ol>
    </section>
    <section class="content">

        <div class="box">
            <div class="box-header">
                <h3 class="box-title">Cihaz Listesi</h3>
            </div>
            
            <!-- /.box-header -->
            <div class="box-body">
                <div style="margin-bottom:10px; text-align:right;">
                    <a  class="btn btn-success ModalPopup" data-post-url="/Device/New" data-height="320px">Yeni Cihaz Ekle</a>
                </div>
                <table id="dtDevices" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Cihaz İsmi</th>
                            <th>Son Yapılan İşlem Tarihi</th>
                            <th>Cihaz Kayıt Tarihi</th>
                            <th>Durum</th>
                            <th>İşlem</th>
                        </tr>
                    </thead>
                    <tbody>
                      
                    </tbody>

                </table>
            </div>
            <!-- /.box-body -->
        </div>

    </section>
</div>

CloudBackup.WebApp/Views/Device/New.cshtml
@model CloudBackup.Database.ViewModel.CreateModel.DeviceInsertModel
@{
    Layout = "_ModalLayout";
}
@section Scripts{

    <script>
        $(document).ready(function () {

        @if(Model.CloseModal)
        {
            @:top.$('#modal-').modal('toggle');
        }

        $(".CloseModal").click(function () {
                    top.$('#modal-').modal('toggle');
                });
        });
    </script>
}
@section Heads {

}

<div class="modal-header">
    <button type="button" class="close CloseModal" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Cihaz Ekle</h4>
</div>
<form role="form" asp-controller="Device" asp-action="New">
    <div class="modal-body">
        <input type="hidden" asp-for="HashedDeviceId" />
        <!-- text input -->
        <div class="form-group">
            <label>Cihaz Adı </label>
            <input type="text" asp-for="DeviceName" class="form-control" placeholder="Cihaz İsmi Giriniz">
        </div>
        <!-- text input -->
        <div class="form-group">
            <label>Cihaz Açıklaması </label>
            <textarea type="text" asp-for="DeviceDescription" class="form-control" placeholder="Cihaz Açıklaması Giriniz"></textarea>
        </div>



    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default pull-left CloseModal" data-dismiss="modal">Kapat</button>
        @if (String.IsNullOrEmpty(Model.HashedDeviceId))
        {
            <button type="submit" class="btn btn-primary">Ekle</button>
        }
        else
        {
            <button type="submit" class="btn btn-primary">Düzenle</button>
        }
    </div>

</form>

CloudBackup.WebApp/Views/Device/NewJob.cshtml
@model CloudBackup.Database.ViewModel.CreateModel.DevicePlanInsertModel
@{
    Layout = "_ModalLayout";
    List<CloudBackup.Database.ViewModel.ViewSelectList> planList = (List<CloudBackup.Database.ViewModel.ViewSelectList>)ViewBag.Platforms;
}

@section Scripts{
    <script src="~/Scripts/device_newjob.js"></script>
    <script>
         function ChooseDirectory(directory,htmlElement) {
            $('#' + htmlElement).val(directory); console.log(directory);
        };
        $(document).ready(function () {

            @if(Model.CloseModal)
        {
            @:top.$('#modal-').modal('toggle');
        }

        $(".CloseModal").click(function () {
                    top.$('#modal-').modal('toggle');
                });


            $(".cllickCloudDirectory").click(function () {
                common.openModal('/Device/DirectoryListing?htmlElement=inptRemoteDirectory&cloudId=' + $("#HashedPlanId").val(),'300px')
            });



            device_newjob.init();
        });
    </script>
}
@section Heads {

}

<div class="modal-header">
    <button type="button" class="close CloseModal" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Plan Ekle</h4>
</div>
<form role="form" asp-action="NewJob" asp-controller="Device">
    <div class="modal-body">
        <input type="hidden" asp-for="HashedDevicePlanId" />
        <input type="hidden" asp-for="DeviceHashedId" />
        <!-- text input -->
        <div class="form-group">
            <label>Plan Adı </label>
            <input type="text" asp-for="Name" class="form-control" placeholder="Plan Adını Giriniz">
        </div>
        <!-- text input -->
        <div class="form-group">
            <label>Plan Açıklaması </label>
            <textarea type="text" asp-for="Description" class="form-control" placeholder="Plan Açıklaması Giriniz"></textarea>
        </div>
        <div class="form-group">
            <label>Yedeklenecek İşleminin Başlayacağı Tarih Saat  </label>
            <div class="input-group date" style="float:left; width:50%;">
                <div class="input-group-addon">
                    <i class="fa fa-calendar"></i>
                </div>
                <input type="text" asp-for="BackupStartDate" class="form-control pull-right" id="datepicker">
            </div>
            <div class="input-group" style="float:left; width:50%;">
                <input asp-for="BackupStartTime" type="text" class="form-control timepicker">
                <div class="input-group-addon">
                    <i class="fa fa-clock-o"></i>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="form-group">
            <label>Yedekleme Sıklığı</label>
            <select asp-for="RetryPlan" class="form-control">
                @foreach (var item in Enum.GetValues(typeof(CloudBackup.Database.Enum.RetryPlan)))
                {
                    CloudBackup.Database.Enum.RetryPlan pl = ((CloudBackup.Database.Enum.RetryPlan)(int)item);
                    if (pl == CloudBackup.Database.Enum.RetryPlan.OneTime)
                    {
                        <option value="@((int)item)">Bir kere </option>
                    }
                    if (pl == CloudBackup.Database.Enum.RetryPlan.Minute30)
                    {
                        <option value="@((int)item)">30 dakika da bir </option>
                    }
                    else if (pl == CloudBackup.Database.Enum.RetryPlan.Hour1)
                    {
                        <option value="@((int)item)"> Her saat </option>
                    }
                    else if (pl == CloudBackup.Database.Enum.RetryPlan.Hour3)
                    {
                        <option value="@((int)item)">3 saate bir </option>
                    }
                    else if (pl == CloudBackup.Database.Enum.RetryPlan.Hour6)
                    {
                        <option value="@((int)item)">6 saate bir </option>
                    }
                    else if (pl == CloudBackup.Database.Enum.RetryPlan.Hour12)
                    {
                        <option value="@((int)item)">12 saate bir </option>
                    }
                    else if (pl == CloudBackup.Database.Enum.RetryPlan.Day1)
                    {
                        <option value="@((int)item)">Her Gün</option>
                    }
                    else if (pl == CloudBackup.Database.Enum.RetryPlan.Day2)
                    {
                        <option value="@((int)item)">2 günde bir</option>
                    }
                    else if (pl == CloudBackup.Database.Enum.RetryPlan.Day3)
                    {
                        <option value="@((int)item)">3 günde bir</option>
                    }
                    else if (pl == CloudBackup.Database.Enum.RetryPlan.Day4)
                    {
                        <option value="@((int)item)">4 günde bir</option>
                    }
                    else if (pl == CloudBackup.Database.Enum.RetryPlan.Day5)
                    {
                        <option value="@((int)item)">5 günde bir</option>
                    }
                    else if (pl == CloudBackup.Database.Enum.RetryPlan.Day6)
                    {
                        <option value="@((int)item)">6 günde bir</option>
                    }
                    else if (pl == CloudBackup.Database.Enum.RetryPlan.Day7)
                    {
                        <option value="@((int)item)">7 günde bir</option>
                    }
                    else if (pl == CloudBackup.Database.Enum.RetryPlan.Day8)
                    {
                        <option value="@((int)item)">8 günde bir</option>
                    }
                    else if (pl == CloudBackup.Database.Enum.RetryPlan.Day9)
                    {
                        <option value="@((int)item)">9 günde bir</option>
                    }
                    else if (pl == CloudBackup.Database.Enum.RetryPlan.Day10)
                    {
                        <option value="@((int)item)">10 günde bir</option>
                    }
                    else if (pl == CloudBackup.Database.Enum.RetryPlan.Month1)
                    {
                        <option value="@((int)item)">Ayda bir</option>
                    }
                    else if (pl == CloudBackup.Database.Enum.RetryPlan.Month2)
                    {
                        <option value="@((int)item)">2 ayda bir</option>
                    }
                    else if (pl == CloudBackup.Database.Enum.RetryPlan.Month3)
                    {
                        <option value="@((int)item)">3 ayda bir</option>
                    }
                    else if (pl == CloudBackup.Database.Enum.RetryPlan.Month4)
                    {
                        <option value="@((int)item)">4 ayda bir</option>
                    }
                    else if (pl == CloudBackup.Database.Enum.RetryPlan.Year1)
                    {
                        <option value="@((int)item)">Senede bir</option>
                    }
                }
            </select>
        </div>
        <div class="form-group">
            <label>Yedeklenecek Platform</label>
            <select asp-for="HashedPlanId" class="form-control">
                @foreach (var item in planList)
                {
                    if (item.RealId == Model.PlanId)
                    {
                        <option selected="selected" value="@item.Id">@item.Text</option>
                    }
                    else
                    {
                        <option value="@item.Id">@item.Text</option>
                    }

                }
            </select>
        </div>
        <div class="" style="margin-bottom:15px;">
            <label>Bilgisayarda Yedeklenecek Klasör</label>

            <div class="input-group">
                <div class="input-group-btn">
                    <a class="btn btn-danger ModalPopup" data-post-url="/Device/DirectoryListing?htmlElement=inptLocalDirectory&deviceId=@Model.DeviceHashedId" data-height="300px">Seç</a>
                </div>
                <!-- /btn-group -->
                <input id="inptLocalDirectory" asp-for="LocalSource" type="text" class="form-control">
            </div>
        </div>
        <div class="" style="margin-bottom:15px;">
            <label>Bulutta Yedeklenecek Klasör</label>

            <div class="input-group">
                <div class="input-group-btn">
                    <a class="btn btn-danger cllickCloudDirectory" >Seç</a>
                </div>
                <!-- /btn-group -->
                <input id="inptRemoteDirectory" asp-for="RemoteSource" type="text" class="form-control">
            </div>
        </div>

    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default pull-left CloseModal" data-dismiss="modal">Kapat</button>
        @if (String.IsNullOrEmpty(Model.HashedDevicePlanId))
        {
            <button type="submit" class="btn btn-primary">Ekle</button>
        }
        else
        {
            <button type="submit" class="btn btn-primary">Düzenle</button>
        }

    </div>

</form>